# This file generated by Quarto; do not edit by hand.

from __future__ import annotations

from pathlib import Path
from shiny import App, Inputs, Outputs, Session, ui




def server(input: Inputs, output: Outputs, session: Session) -> None:
    #import json
    #import pprint
    from pathlib import Path
    from functools import cache
    from IPython.display import display

    from shiny import render, ui


    import duckdb
    import folium
    import pandas as pd
    import shiny

    # ========================================================================

    HEALTHKIT_DB = "../data/healthkit-sqlite-2023-11-17-fix.db"

    # ========================================================================

    CAMINO_SQL = """
        SELECT id, duration, sourceName, creationDate, startDate, endDate, workout_statistics, device 
        FROM workouts 
        WHERE sourceName != 'AllTrails' 
        AND (
            (startDate >= '2023-10-10' AND startDate <= '2023-10-17' AND duration > 100) 
            OR 
            (startDate >= '2023-10-16' AND startDate <= '2023-10-17' AND duration < 100)
        )
        """

    # ========================================================================

    WALK_SQL = """
        SELECT * FROM workout_points 
        WHERE workout_id = 'WORKOUT_ID'
        """

    # ========================================================================

    CAMINO_STATS_SQL = """
        SELECT * FROM workouts WHERE sourceName != 'AllTrails' AND startDate >= '2023-10-16' AND startDate <= '2023-10-17' 
        AND duration < 100
        """

    # ========================================================================

    if Path(HEALTHKIT_DB).exists():
        con = duckdb.connect(HEALTHKIT_DB)
        con.install_extension("sqlite")
        con.load_extension("sqlite")

    # ========================================================================

    con.sql("PRAGMA show_tables").to_df() ;

    # ========================================================================

    stats_df = con.sql(CAMINO_STATS_SQL).to_df()
    # pprint.pprint(stats_df["workout_statistics"].iloc[0]) 
    # json.loads(stats_df["workout_statistics"].iloc[0])[0]

    # ========================================================================

    workouts_df = con.sql(CAMINO_SQL).to_df()

    # ========================================================================

    @cache
    def get_walk_data(id):
        """
        Fetch and process walk data for a given ID.
        This function is cached to avoid repeated database queries for the same ID.
        """
        walk_df = con.sql(WALK_SQL.replace("WORKOUT_ID", id)).to_df()
        # Any additional processing can be done here
        return walk_df

    # ========================================================================

    walk_ids = workouts_df["id"].values.tolist()[1:]   # Discard evening walk in San Sebastin

    # ========================================================================

    def load_walk_data(walk_ids):
        for i, id in enumerate(walk_ids):
            #print(f"#{i+1} - Getting data for walk ID: {id}")
            get_walk_data(id)
        return None

    # ========================================================================

    load_walk_data(walk_ids)

    # ========================================================================

    def update_map(m, df, colour="blue", line_width=3.5):
        points = df[["latitude", "longitude"]].values.tolist()
        folium.PolyLine(points, color=colour, weight=line_width, opacity=1).add_to(m)
        folium.Marker([df["latitude"].iloc[0], df["longitude"].iloc[0]]).add_to(m)
        return m

    # ========================================================================

    def create_walk_map(walk_ids, colour, line_width):
        m = folium.Map(location=[43.3183, -1.9812], zoom_start=12, tiles="openstreetmap")
        for id in walk_ids:
            walk_df = get_walk_data(id)  # Use the cached function
            m = update_map(m, walk_df, colour, line_width)
        m.fit_bounds(m.get_bounds())
        return m

    # ========================================================================

    ## {.sidebar}

    ui.input_select("line_color", "Choose Line Color", choices=["red", "blue", "green", "yellow"])
    ui.input_slider("line_width", "Select Line Width", min=1, max=10, value=3)

    # ========================================================================

    #@render.plot
    def display_map_ui():
        try:
            colour = input.line_color()
            width = input.line_width()
        except:
            colour = "blue"
            width = 3 
        map = create_walk_map(walk_ids, colour, width)
        display(map)

    # ========================================================================

    # display_map_ui() if removing decorator to check in notebook

    # ========================================================================



    return None


_static_assets = ["buen-camino_files","buen-camino_files/libs/quarto-html/tippy.css","buen-camino_files/libs/quarto-html/quarto-syntax-highlighting.css","buen-camino_files/libs/bootstrap/bootstrap-icons.css","buen-camino_files/libs/bootstrap/bootstrap.min.css","buen-camino_files/libs/quarto-dashboard/datatables.min.css","buen-camino_files/libs/clipboard/clipboard.min.js","buen-camino_files/libs/quarto-html/quarto.js","buen-camino_files/libs/quarto-html/popper.min.js","buen-camino_files/libs/quarto-html/tippy.umd.min.js","buen-camino_files/libs/quarto-html/anchor.min.js","buen-camino_files/libs/bootstrap/bootstrap.min.js","buen-camino_files/libs/quarto-dashboard/quarto-dashboard.js","buen-camino_files/libs/quarto-dashboard/stickythead.js","buen-camino_files/libs/quarto-dashboard/datatables.min.js","buen-camino_files/libs/quarto-dashboard/pdfmake.min.js","buen-camino_files/libs/quarto-dashboard/vfs_fonts.js","buen-camino_files/libs/quarto-dashboard/web-components.js","buen-camino_files/libs/quarto-dashboard/components.js"]
_static_assets = {"/" + sa: Path(__file__).parent / sa for sa in _static_assets}

app = App(
    Path(__file__).parent / "buen-camino.html",
    server,
    static_assets=_static_assets,
)
